@startuml
'https://plantuml.com/component-diagram


package euler {

agent engine
agent graphics
agent gui
agent util
agent physics
agent vulkan

}

package extern {
agent glm
agent mruby
agent SDL3
agent Vulkan
agent VulkanMemoryAllocator
agent Nuklear
}

gui --> graphics
gui --> vulkan
gui ..> Nuklear
graphics --> vulkan
engine --> graphics
engine --> gui
engine --> util
engine --> vulkan
engine --> physics
util --> SDL3
util --> mruby
physics --> glm
physics --> vulkan
vulkan --> Vulkan
physics --> util
graphics --> util
graphics --> SDL3
vulkan --> util
vulkan --> VulkanMemoryAllocator
vulkan --> SDL3

@enduml